# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Trokhymenko Vladyslav
title: Unreal Engime Gameplay Programmer
email: mrsadtxxx999@gmail.com
website: https://mrsadt.github.io/Portfolio

# Dark Mode (true/false/never)
darkmode: true

# Social links
twitter_username: "00000001"
github_username:  mrsadt
# stackoverflow_username: "00000001"
# dribbble_username: ""
# facebook_username: ""
# flickr_username: ""
instagram_username: ""
linkedin_username: ""
# xing_username: ""
# pinterest_username: ""
youtube_username: MrSadT_
# googleplus_username: +""
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: itch.io
  icon: fas fa-globe
  url: https://itch.io/profile/mrsadt
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Vlad and I'm a 17 y.o. unreal engine gameplay programmer. I also have experience making scripts, 3d and 2d.  I have only worked for one company, where I acquired teamwork and responsibility skills.

  I have a strong understanding : <mark>Unreal Engine Core</mark> / <mark>modules</mark>, <mark>reflection</mark>, <mark>Perforce</mark>, <mark>Git</mark> ,<mark>C++ / Blueprints</mark>, <mark>Multiplayer</mark>, <mark>Gameplay Ability System</mark>, <mark>AnimationBlueprint</mark> / <mark>IK</mark> / <mark>Control Rig</mark>,  <mark>UMG / Widgets</mark>, <mark>BehaviorTree</mark>, some<mark> materials<mark> and <mark>3d modeling<mark>.

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Example of work
        link: github.com/MrSadT/UE5-Interaction-system-for-multiplayer-via-GAS
        # link_text: Project Website
        additional_links:
          - title:  UE5-Interaction-system-for-multiplayer-via-GAS
            icon: fab fa-github
            url: github.com/MrSadT/UE5-Interaction-system-for-multiplayer-via-GAS
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          This is probably one of the best and simple system for interaction for FPS and TPS projects
        description: | # this will include new lines to allow paragraphs
          I started this project as a way if learning <mark>GAS</mark> and it has since grown into one of the best and simple interaction system. 
          I have learned many skills through this and been I'm very proud of having this in my portfolio. If you need interaction in your project I would advise you to use this one.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Bashies&BivouacGames
        link: bashiesbivouacgames.itch.io
        # link_text: boringcompany.com
        sub_title: Gameplay Programmer
        caption: July 2025 - October 2025
        quote: >
          Working in a small indie team of passionate developers, I focus on gameplay programming and systems design.
        description: | # this will include new lines to allow paragraphs
            My main responsibilities include implementing player mechanics, AI behaviors, etc in Unreal Engine. I enjoy solving creative technical challenges and bringing unique gameplay ideas to life through code.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Self-Taught Developer
        caption: 2021 - Present
        sub_title: Online Learning & Personal Projects
        quote: >
          I started with C# and Unity, but realized it wasn't for me and switched to Unreal Engine.
        description: | # this will include new lines to allow paragraphs
          After discovering my passion for game development, I began teaching myself programming and game design through online courses, documentation, and community projects.
          
          This self-driven approach taught me discipline, problem solving, and how to learn new technologies quickly.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Outside of coding and experimenting with new gameplay ideas, I’m also interested in:
      - Server-side development and backend logic for multiplayer systems
      - Unix-based environments and shell scripting
      - Networking protocols, optimization, and server management
      - Performance profiling and debugging tools
      - Automation and CI/CD pipelines for game builds

      "I love turning ideas into something you can play."

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
